module.exports = {
    isEmpty: require('./isEmpty'),
    isBlank: require('./isBlank'),
    startsWith: require('./startsWith'),
    endsWith: require('./endsWith'),
    before: require('./before'),
    beforeLast: require('./beforeLast'),
    after: require('./after'),
    afterLast: require('./afterLast'),
    between: require('./between'),
    pad: require('./pad'),
    lpad: require('./lpad'),
    rpad: require('./rpad'),
    lrpad: require('./lrpad'),
    lines: require('./lines'),
    repeat: require('./repeat'),
    truncate: require('./truncate'),
    escapeHTML: require('./escapeHTML'),
    unescapeHTML: require('./unescapeHTML'),
    hashCode: require('./hashCode'),
    toString: require('./toString')
};
