module.exports = {
    isEmpty: ('./isEmpty'),
    isBlank: ('./isBlank'),
    startsWith: ('./startsWith'),
    endsWith: ('./endsWith'),
    before: ('./before'),
    beforeLast: ('./beforeLast'),
    after: ('./after'),
    afterLast: ('./afterLast'),
    between: ('./between'),
    pad: ('./pad'),
    lpad: ('./lpad'),
    rpad: ('./rpad'),
    lrpad: ('./lrpad'),
    lines: ('./lines'),
    repeat: ('./repeat'),
    truncate: ('./truncate'),
    escapeHTML: ('./escapeHTML'),
    unescapeHTML: ('./unescapeHTML'),
    hashCode: ('./hashCode'),
    toString: ('./toString')
};
